已连接到 vul-detect (Python 3.9.21)

In [1]:
import dgl
import pandas as pd

In [2]:
data = pd.read_pickle("/root/autodl-tmp/naturalcc/examples/counterfactual-vulnerability-detection/cfexplainer/storage/processed/vul_graph_dataset/train_processed/dataframe.pkl")


data.head()

,idx,dataset,id,label,removed,added,diff,before,after,vul,valid,torch_geometrics_data
0,0,bigvul,177808,train,[],"[42, 43]",zset_outputintent(i_ctx_t * i_ctx_p)\n {\n ...,zset_outputintent(i_ctx_t * i_ctx_p)\n {\n ...,zset_outputintent(i_ctx_t * i_ctx_p)\n {\n ...,1,True,"[[(x, tensor([[ 0.0161, -0.0272, 0.0047, ......"
1,1,bigvul,179080,train,[],[35],"SYSCALL_DEFINE1(inotify_init1, int, flags)\n ...","SYSCALL_DEFINE1(inotify_init1, int, flags)\n ...","SYSCALL_DEFINE1(inotify_init1, int, flags)\n ...",1,True,"[[(x, tensor([[-0.0035, -0.0155, 0.0044, ......"
2,2,bigvul,179136,train,[116],"[7, 117, 118]","int wvlan_uil_put_info(struct uilreq *urq, st...","int wvlan_uil_put_info(struct uilreq *urq, st...","int wvlan_uil_put_info(struct uilreq *urq, st...",1,True,"[[(x, tensor([[-0.0107, -0.0186, -0.0028, ......"
3,3,bigvul,179169,train,"[19, 26]","[20, 27]","static int filter_frame(AVFilterLink *inlink,...","static int filter_frame(AVFilterLink *inlink,...","static int filter_frame(AVFilterLink *inlink,...",1,True,"[[(x, tensor([[ 0.0002, -0.0244, -0.0047, ......"
4,4,bigvul,179347,train,"[64, 65, 68, 72, 73, 76, 89, 94, 125]","[22, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 3...",static unsigned xen_netbk_tx_build_gops(struc...,static unsigned xen_netbk_tx_build_gops(struc...,static unsigned xen_netbk_tx_build_gops(struc...,1,True,"[[(x, tensor([[ 3.0888e-03, -2.1401e-02, 3.87..."

In [6]:
devign = pd.read_json("/root/autodl-tmp/vul-detect/data/raw/dataset.json")
devign.head()

,project,commit_id,target,func
0,FFmpeg,973b1a6b9070e2bf17d17568cbaf4043ce931f51,0,static av_cold int vdadec_init(AVCodecContext ...
1,FFmpeg,321b2a9ded0468670b7678b7c098886930ae16b2,0,static int transcode(AVFormatContext **output_...
2,FFmpeg,5d5de3eba4c7890c2e8077f5b4ae569671d11cf8,0,"static void v4l2_free_buffer(void *opaque, uin..."
3,FFmpeg,32bf6550cb9cc9f487a6722fe2bfc272a93c1065,0,"int ff_get_wav_header(AVFormatContext *s, AVIO..."
4,FFmpeg,57d77b3963ce1023eaf5ada8cba58b9379405cc8,0,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ..."

In [8]:
devign.shape

(27318, 4)

In [10]:
import glob
files = glob.glob("/root/autodl-tmp/vul-detect/utils/data/torch_geometrics_process/cfexplainer/storage/processed/Devign/code/*.c")
len(files)

4608

In [7]:
def Filter_raw_dataset(raw):

    # Here, taking the Devign dataset as an example,
    # specific modifications need to be made according to different dataset formats.
    print(f"=== Raw dataset size: {len(raw)} ===")
    filtered = data.apply_filter(raw, filter_select) # see "select" function above
    print(f"=== Filtered dataset size: {len(filtered)} ===")
    filtered = data.clean(filtered) # remove duplicates 
    print(f"=== Filtered and cleaned dataset size: {len(filtered)} ===")
    data.drop(filtered, ["hash", "commit_id", "project", "cwe"]) # Hash column name "hash" or "commit_id" depends on the dataset
    filtered['idx'] = filtered.index
    print(f"=== Filtered and cleaned dataset columns: {filtered.columns} ===")

    return filtered

Filter_raw_dataset(devign)

=== Raw dataset size: 27318 ===

AttributeError: 'DataFrame' object has no attribute 'apply_filter'

In [4]:
data.columns

Index(['idx', 'dataset', 'id', 'label', 'removed', 'added', 'diff', 'before',
       'after', 'vul', 'valid', 'torch_geometrics_data'],
      dtype='object')

已连接到 vul-detect (Python 3.9.21)

In [ ]:
data["torch_geometrics_data"][0][0]

Data(x=[117, 768], edge_index=[2, 199], _VULN=[117], _LINE=[117], _SAMPLE=[117], _GTYPE='ast')

In [ ]:
data["torch_geometrics_data"][0][0].edge_index

tensor([[  0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   2,   3,   4,   6,  11,  13,  14,
          15,  16,  17,  18,  19,  19,  20,  21,  21,  21,  21,  21,  22,  23,
          23,  24,  25,  26,  26,  27,  28,  28,  29,  30,  31,  31,  32,  33,
          33,  34,  35,  36,  37,  38,  38,  39,  40,  41,  41,  42,  42,  42,
          43,  44,  45,  45,  45,  46,  47,  48,  48,  49,  49,  50,  51,  51,
          51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,
          51,  51,  51,  51,  51,  55,  56,  59,  60,  63,  64,  67,  72,  72,
          72,  73,  74,  75,  76,  77,  77,  77,  80,  81,  82,  83,  84,  85,
          86,  86,  86,  86,  87,  87,  89,  90,  90,  91,  91,  91,  91,  92,
          93,  94,  95,  96,  96,  97,  97,  97,  97,  97,  97,  97,  97,  97,
          97,  97,  97,  97,  97,  97,  99, 100, 100, 104, 105, 105, 109, 110,
         110, 115, 116],
        [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  21,  28,  30,  31,  33,  35,  36,  37,
          38,  40,  41,  45,  48,  51,  72,  75,  76,  77,  80,  81,  82,  83,
          84,  85,  86,  95,  96, 115, 116,   2,   3,   4,   6,  11,  13,  14,
          15,  16,  17,  18,  19,  20,  20,  21,  22,  23,  25,  26,  22,  23,
          24,  24,  25,  26,  27,  27,  28,  29,  29,  30,  31,  32,  32,  33,
          34,  34,  35,  36,  37,  38,  39,  39,  40,  41,  42,  42,  43,  44,
          43,  44,  45,  46,  47,  46,  47,  48,  49,  49,  50,  50,  51,  52,
          53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
          67,  68,  69,  70,  71,  55,  56,  59,  60,  63,  64,  67,  72,  73,
          74,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
          86,  90,  87,  89,  87,  88,  89,  90,  91,  91,  92,  93,  94,  92,
          93,  94,  95,  96,  97,  97,  98,  99, 100, 102, 103, 104, 105, 107,
         108, 109, 110, 112, 113, 114,  99, 100, 101, 104, 105, 106, 109, 110,
         111, 115, 116]])

In [ ]:
data["torch_geometrics_data"][0][0].edge_index[0]

tensor([  0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   2,   3,   4,   6,  11,  13,  14,
         15,  16,  17,  18,  19,  19,  20,  21,  21,  21,  21,  21,  22,  23,
         23,  24,  25,  26,  26,  27,  28,  28,  29,  30,  31,  31,  32,  33,
         33,  34,  35,  36,  37,  38,  38,  39,  40,  41,  41,  42,  42,  42,
         43,  44,  45,  45,  45,  46,  47,  48,  48,  49,  49,  50,  51,  51,
         51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,
         51,  51,  51,  51,  51,  55,  56,  59,  60,  63,  64,  67,  72,  72,
         72,  73,  74,  75,  76,  77,  77,  77,  80,  81,  82,  83,  84,  85,
         86,  86,  86,  86,  87,  87,  89,  90,  90,  91,  91,  91,  91,  92,
         93,  94,  95,  96,  96,  97,  97,  97,  97,  97,  97,  97,  97,  97,
         97,  97,  97,  97,  97,  97,  99, 100, 100, 104, 105, 105, 109, 110,
        110, 115, 116])

In [ ]:
type(data["torch_geometrics_data"][0][0].edge_index[0])

torch.Tensor

In [ ]:
data["torch_geometrics_data"][0][0].edge_index[0].shape

torch.Size([199])

In [ ]:
graph_data = {
                ('node', 'ast', 'node'): (data["torch_geometrics_data"][0][0].edge_index[0], data["torch_geometrics_data"][0][0].edge_index[1]),
                ('node', 'cfgcdg', 'node'): (data["torch_geometrics_data"][0][1].edge_index[0], data["torch_geometrics_data"][0][1].edge_index[1]),
                ('node', 'pdg', 'node'): (data["torch_geometrics_data"][0][2].edge_index[0], data["torch_geometrics_data"][0][2].edge_index[1])
            }
het_graph = dgl.heterograph(graph_data)

In [ ]:
het_graph

Graph(num_nodes={'node': 117},
      num_edges={('node', 'ast', 'node'): 199, ('node', 'cfgcdg', 'node'): 334, ('node', 'pdg', 'node'): 454},
      metagraph=[('node', 'node', 'ast'), ('node', 'node', 'cfgcdg'), ('node', 'node', 'pdg')])

In [ ]:
data["torch_geometrics_data"][0][0].x

tensor([[ 0.0161, -0.0272,  0.0047,  ..., -0.0196, -0.0699, -0.0344],
        [-0.0278,  0.0005,  0.0489,  ..., -0.0783, -0.0631, -0.0043],
        [-0.0099, -0.0376,  0.0407,  ..., -0.0036, -0.0370, -0.0257],
        ...,
        [ 0.0820, -0.0227, -0.0427,  ..., -0.0036,  0.0008,  0.0366],
        [ 0.0062, -0.0362,  0.0056,  ..., -0.0786, -0.0375, -0.0339],
        [ 0.0508, -0.0282, -0.0458,  ..., -0.0300, -0.0455, -0.0338]])

In [ ]:
data["torch_geometrics_data"][0][0].x.shape

torch.Size([117, 768])

In [ ]:
het_graph.ndata['feature'] = data["torch_geometrics_data"][0][0].x

In [ ]:
import torch

In [ ]:
import scipy.sparse as sp

In [ ]:
def sparse_mx_to_torch_sparse_tensor(sparse_mx):
    """Convert a scipy sparse matrix to a torch sparse tensor."""
    sparse_mx = sparse_mx.tocoo().astype(np.float32)
    indices = torch.from_numpy(
        np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
    values = torch.from_numpy(sparse_mx.data)
    shape = torch.Size(sparse_mx.shape)
    return torch.sparse.FloatTensor(indices, values, shape)

In [ ]:
def normalize_adj(row, col):
    """Symmetrically normalize adjacency matrix."""
    data = torch.ones(row.size(1))
    adj = sp.coo_matrix((data, (row, col)), shape=(het_graph.num_nodes(), het_graph.num_nodes(),))
    rowsum = np.array(adj.sum(1))

    d_inv_sqrt = np.power(rowsum, -0.5).flatten()
    d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.
    d_mat_inv_sqrt = sp.diags(d_inv_sqrt)
    return adj.dot(d_mat_inv_sqrt).transpose().dot(d_mat_inv_sqrt).tocoo()

In [ ]:
def normalize_adj(row, col):
    """Symmetrically normalize adjacency matrix."""
    data = torch.ones(row.size(0))

    adj = sp.coo_matrix((data, (row, col)), shape=(het_graph.num_nodes(), het_graph.num_nodes(),))
    rowsum = np.array(adj.sum(1))

    d_inv_sqrt = np.power(rowsum, -0.5).flatten()
    d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.
    d_mat_inv_sqrt = sp.diags(d_inv_sqrt)
    return adj.dot(d_mat_inv_sqrt).transpose().dot(d_mat_inv_sqrt).tocoo()

In [ ]:
import numpy as np

In [ ]:
normalize_adj(data["torch_geometrics_data"][0][0].edge_index[0], data["torch_geometrics_data"][0][0].edge_index[1])

<ipython-input-30-0d254a890e93>:8: RuntimeWarning: divide by zero encountered in power
  d_inv_sqrt = np.power(rowsum, -0.5).flatten()

<117x117 sparse matrix of type '<class 'numpy.float32'>'
	with 166 stored elements in COOrdinate format>

In [ ]:
meta_path_adj_with_normalize_adj = {
                'ast': sparse_mx_to_torch_sparse_tensor(normalize_adj(data["torch_geometrics_data"][0][0].edge_index[0], data["torch_geometrics_data"][0][0].edge_index[1])),
                'cfgcdg': sparse_mx_to_torch_sparse_tensor(normalize_adj(data["torch_geometrics_data"][0][1].edge_index[0], data["torch_geometrics_data"][0][1].edge_index[1])),
                'pdg': sparse_mx_to_torch_sparse_tensor(normalize_adj(data["torch_geometrics_data"][0][2].edge_index[0], data["torch_geometrics_data"][0][2].edge_index[1]))
            }

<ipython-input-30-0d254a890e93>:8: RuntimeWarning: divide by zero encountered in power
  d_inv_sqrt = np.power(rowsum, -0.5).flatten()
<ipython-input-26-064c30c72962>:8: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:605.)
  return torch.sparse.FloatTensor(indices, values, shape)

In [ ]:
meta_path_adj_with_normalize_adj['ast']

tensor(indices=tensor([[  0,   1,   2,   3,   4,   6,  11,  13,  14,  15,  16,
                         17,  18,  19,  21,  28,  30,  31,  33,  35,  36,  37,
                         38,  40,  41,  45,  48,  51,  72,  75,  76,  77,  80,
                         81,  82,  83,  84,  85,  86,  95,  96, 115, 116,   2,
                          3,   4,   6,  11,  13,  14,  15,  16,  17,  18,  19,
                         20,  20,  21,  22,  23,  25,  26,  22,  23,  24,  24,
                         25,  26,  27,  27,  28,  29,  29,  30,  31,  32,  32,
                         33,  34,  34,  35,  36,  37,  38,  39,  39,  40,  41,
                         42,  42,  43,  44,  43,  44,  45,  46,  47,  46,  47,
                         48,  49,  49,  50,  50,  51,  55,  56,  59,  60,  63,
                         64,  67,  55,  56,  59,  60,  63,  64,  67,  72,  73,
                         74,  73,  74,  75,  76,  77,  80,  81,  82,  83,  84,
                         85,  86,  87,  89,  90,  87,  89,  90,  91,  91,  92,
                         93,  94,  92,  93,  94,  95,  96,  97,  97,  99, 100,
                        104, 105, 109, 110,  99, 100, 104, 105, 109, 110, 115,
                        116],
                       [  0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   1,
                          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
                          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
                          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,
                          3,   4,   6,  11,  13,  14,  15,  16,  17,  18,  19,
                         19,  20,  21,  21,  21,  21,  21,  22,  23,  23,  24,
                         25,  26,  26,  27,  28,  28,  29,  30,  31,  31,  32,
                         33,  33,  34,  35,  36,  37,  38,  38,  39,  40,  41,
                         41,  42,  42,  42,  43,  44,  45,  45,  45,  46,  47,
                         48,  48,  49,  49,  50,  51,  51,  51,  51,  51,  51,
                         51,  51,  55,  56,  59,  60,  63,  64,  67,  72,  72,
                         72,  73,  74,  75,  76,  77,  80,  81,  82,  83,  84,
                         85,  86,  86,  86,  86,  87,  89,  90,  90,  91,  91,
                         91,  91,  92,  93,  94,  95,  96,  96,  97,  97,  97,
                         97,  97,  97,  97,  99, 100, 104, 105, 109, 110, 115,
                        116]]),
       values=tensor([0.5000, 0.1031, 0.1459, 0.1459, 0.1459, 0.1459, 0.1459,
                      0.1459, 0.1459, 0.1459, 0.1459, 0.1459, 0.1459, 0.1031,
                      0.0652, 0.1031, 0.1459, 0.1031, 0.1031, 0.1459, 0.1459,
                      0.1459, 0.1031, 0.1459, 0.1031, 0.0842, 0.1031, 0.0318,
                      0.0842, 0.1459, 0.1459, 0.0842, 0.1459, 0.1459, 0.1459,
                      0.1459, 0.1459, 0.1459, 0.0729, 0.1459, 0.1031, 0.1459,
                      0.1459, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
                      1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.5000, 0.7071,
                      1.0000, 0.2000, 0.4472, 0.3162, 0.4472, 0.3162, 1.0000,
                      0.5000, 0.7071, 1.0000, 1.0000, 0.5000, 0.7071, 1.0000,
                      0.5000, 0.7071, 1.0000, 1.0000, 0.5000, 0.7071, 1.0000,
                      0.5000, 0.7071, 1.0000, 1.0000, 1.0000, 1.0000, 0.5000,
                      0.7071, 1.0000, 1.0000, 0.5000, 0.4082, 0.3333, 0.5774,
                      0.5774, 1.0000, 1.0000, 0.3333, 0.5774, 0.5774, 1.0000,
                      1.0000, 0.5000, 0.5000, 0.5000, 0.7071, 1.0000, 0.0476,
                      0.2182, 0.2182, 0.2182, 0.2182, 0.2182, 0.2182, 0.2182,
                      1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
                      0.3333, 0.5774, 0.5774, 1.0000, 1.0000, 1.0000, 1.0000,
                      0.3333, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
                      0.2500, 0.3536, 0.5000, 0.3536, 0.5000, 1.0000, 0.5000,
                      0.3536, 0.2500, 0.5000, 0.5000, 0.5000, 1.0000, 1.0000,
                      1.0000, 1.0000, 0.5000, 0.1826, 0.0667, 0.2582, 0.1826,
                      0.2582, 0.1826, 0.2582, 0.1826, 1.0000, 0.5000, 1.0000,
                      0.5000, 1.0000, 0.5000, 1.0000, 1.0000]),
       size=(117, 117), nnz=166, layout=torch.sparse_coo)

In [ ]:
def re_featuresv2(adj, features, K, start_hops=0):
    nodes_features = torch.empty(features.shape[0], 1, K + 1 - start_hops, features.shape[1])

    for i in range(features.shape[0]):  # self
        nodes_features[i, 0, 0, :] = features[i]

    x = features + torch.zeros_like(features)

    for i in range(K):  # 0:1-hop，1：2:-hop....k-1:K-hop

        x = torch.matmul(adj, x)
        if i >= start_hops:
            for index in range(features.shape[0]):
                nodes_features[index, 0, i + 1 - start_hops, :] = x[index]

    nodes_features = nodes_features.squeeze()
    return nodes_features  # size= (N, 1, K+1-start_hops, d )

In [ ]:
multi_hop_features = None
for max_hop in range(1, 10):
    multi_hop_features_with_process_feature_with_normalize_adj = [re_featuresv2(adj=meta_path_adj_with_normalize_adj[mp], features=data["torch_geometrics_data"][0][0].x, K=max_hop, start_hops=0) for mp in meta_path_adj_with_normalize_adj]

    multi_hop_features_with_process_feature_with_normalize_adj = torch.stack(multi_hop_features_with_process_feature_with_normalize_adj).permute(1, 0, 2, 3)
    if max_hop == 9:
        multi_hop_features = multi_hop_features_with_process_feature_with_normalize_adj

In [ ]:
het_graph.ndata['multi_hop_feature'] = multi_hop_features

In [ ]:
het_graph

Graph(num_nodes={'node': 117},
      num_edges={('node', 'ast', 'node'): 199, ('node', 'cfgcdg', 'node'): 334, ('node', 'pdg', 'node'): 454},
      metagraph=[('node', 'node', 'ast'), ('node', 'node', 'cfgcdg'), ('node', 'node', 'pdg')])

In [1]:
import torch
data = torch.load("/root/autodl-tmp/vul-detect/utils/data/torch_geometrics_process/cfexplainer/storage/processed/CVEfixes/None_processed/dgl_hetgraph_data_ncode.pt")

In [23]:
n = data["graphs"][0].nodes()
e = data["graphs"][0]["pdg"].edges()

In [27]:
e

(tensor([23, 23,  0,  0, 31, 31, 32, 32, 33, 33,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  4,
          4,  4,  4,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  9,  9,  9,
          9, 10, 10, 10, 10, 11, 11, 12, 12, 12, 12, 12, 13, 13, 14, 14, 14, 15,
         15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18,
         19, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 22, 22, 22, 22, 23, 23, 24,
         24, 24, 25, 25, 26, 26, 26, 27, 27, 27, 28, 28, 28, 29, 29, 29, 30, 30,
         30, 31, 32, 33, 34, 34]),
 tensor([31, 23, 23,  0, 31, 32, 33, 32, 33,  0,  7,  3,  2, 11, 18,  5, 25, 30,
         19,  9,  6, 28, 33, 14, 20, 17, 31,  1,  8, 29, 21, 34, 13, 15,  4, 24,
         26, 32, 10, 12, 16, 22, 27,  0,  2,  1,  4,  3,  0,  2, 27,  0,  3,  5,
          0,  4,  6,  0,  5,  0,  6,  7,  9,  8,  0, 24,  7,  0,  8,  0, 10,  9,
         12, 11,  0, 10, 14,  0, 11, 13,  0, 12, 28, 19,  0, 13,  0, 16, 14,  0,
         15, 17, 23,  0, 16, 19, 17, 16, 20, 22, 18, 25,  0, 17, 21, 22, 19, 17,
          0, 20, 19, 28, 21,  0, 20, 21,  0, 21, 22,  0, 17, 22, 23,  0, 24, 25,
          0, 24,  0, 25,  0, 26, 27,  0, 28, 27,  0, 28, 29,  0, 30, 29,  0, 30,
         31,  0,  0, 34,  0, 34]))

In [76]:
import torch
from collections import defaultdict, deque

def compute_deepest_path_pdg(nodes: torch.Tensor, edges: tuple) -> int:
    # 解析边结构
    edge_list = []
    u_tensor, v_tensor = edges  # edges 是 (tensor_u, tensor_v)
    for u, v in zip(u_tensor, v_tensor):
        edge_list.append((u.item(), v.item()))
    
    # 构建邻接表
    adj = defaultdict(list)
    for u, v in edge_list:
        adj[u].append(v)
    
    # Tarjan算法找SCC
    index = 0
    indices = {}
    low_link = {}
    on_stack = set()
    stack = []
    sccs = []
    
    def strongconnect(v):
        # print(v)
        nonlocal index
        indices[v] = index
        low_link[v] = index
        index += 1
        stack.append(v)
        on_stack.add(v)
        
        for w in adj[v]:
            if w not in indices:
                strongconnect(w)
                low_link[v] = min(low_link[v], low_link[w])
            elif w in on_stack:
                low_link[v] = min(low_link[v], indices[w])
        
        if low_link[v] == indices[v]:
            scc = []
            while True:
                w = stack.pop()
                on_stack.remove(w)
                scc.append(w)
                if w == v:
                    break
            sccs.append(scc)
    
    for v in list(adj.keys()):
        if v not in list(indices.keys()):
            strongconnect(v)
    print(sccs)
    # 映射每个节点到所属的SCC
    node_to_scc = {}
    for i, scc in enumerate(sccs):
        for node in scc:
            node_to_scc[node] = i
    
    # 每个SCC的最长路径边数为节点数减一
    scc_lengths = [len(scc) - 1 for scc in sccs]
    
    # 构建缩点后的DAG和逆邻接表
    dag_adj = defaultdict(list)
    reverse_dag_adj = defaultdict(list)
    in_degree = defaultdict(int)
    
    # 添加所有SCC节点（确保孤立节点被包含）
    for scc_id in range(len(sccs)):
        dag_adj[scc_id]  # 确保键存在
    
    # 添加跨SCC的边
    for u, v in edge_list:
        scc_u = node_to_scc[u]
        scc_v = node_to_scc[v]
        if scc_u != scc_v and scc_v not in dag_adj[scc_u]:
            dag_adj[scc_u].append(scc_v)
            reverse_dag_adj[scc_v].append(scc_u)
            in_degree[scc_v] += 1
    
    # 确保所有SCC的入度初始化为0
    for scc_id in range(len(sccs)):
        if scc_id not in in_degree:
            in_degree[scc_id] = 0
    
    # Kahn算法拓扑排序
    queue = deque([scc for scc in dag_adj if in_degree[scc] == 0])
    topo_order = []
    while queue:
        u = queue.popleft()
        topo_order.append(u)
        for v in dag_adj[u]:
            in_degree[v] -= 1
            if in_degree[v] == 0:
                queue.append(v)
    
    # 动态规划计算最长路径
    dp = defaultdict(int)
    max_length = 0
    
    # 确保处理所有SCC（包括孤立节点）
    for scc in range(len(sccs)):
        if scc not in topo_order:
            topo_order.append(scc)
    
    for scc in topo_order:
        current_max = 0
        # 遍历所有前驱scc
        for predecessor in reverse_dag_adj.get(scc, []):
            current_max = max(current_max, dp[predecessor] + 1)
        
        dp[scc] = current_max + scc_lengths[scc]
        max_length = max(max_length, dp[scc])
    
    return max_length

In [104]:
len(data["graphs"])

13463

In [115]:
paths = []
for idx in range(len(data["graphs"])):
    print(idx)
    n = data["graphs"][idx].nodes()
    e = data["graphs"][idx]["pdg"].edges()
    
    a = e[0]
    b = e[1]
    mask = a != b
    a2 = a[mask]
    b2 = b[mask]
    e = (a2, b2)
    
    if(len(e[0]) == 0):
        continue
    # print(e)
    print("最长路径边数:", compute_deepest_path_pdg(n , e))
    paths.append(compute_deepest_path_pdg(n , e))
    print(max(max(a2), max(b2)) == compute_deepest_path_pdg(n , e))

0
[[26, 15, 34, 4, 1, 6, 13, 12, 16, 14, 10, 9, 5, 20, 19, 22, 21, 17, 18, 11, 30, 29, 28, 27, 2, 3, 25, 24, 8, 7, 0, 33, 32, 31, 23]]
最长路径边数: 34
[[26, 15, 34, 4, 1, 6, 13, 12, 16, 14, 10, 9, 5, 20, 19, 22, 21, 17, 18, 11, 30, 29, 28, 27, 2, 3, 25, 24, 8, 7, 0, 33, 32, 31, 23]]
[[26, 15, 34, 4, 1, 6, 13, 12, 16, 14, 10, 9, 5, 20, 19, 22, 21, 17, 18, 11, 30, 29, 28, 27, 2, 3, 25, 24, 8, 7, 0, 33, 32, 31, 23]]
tensor(True)
1
[[2], [4, 3, 0, 1]]
最长路径边数: 4
[[2], [4, 3, 0, 1]]
[[2], [4, 3, 0, 1]]
tensor(True)
2
[[3], [5, 6, 2, 1, 4, 7, 0]]
最长路径边数: 7
[[3], [5, 6, 2, 1, 4, 7, 0]]
[[3], [5, 6, 2, 1, 4, 7, 0]]
tensor(True)
3
[[16, 8, 7, 3, 2, 6, 4, 20, 19, 17, 18, 14, 13, 12, 15, 9, 10, 11, 1, 5, 21, 0]]
最长路径边数: 21
[[16, 8, 7, 3, 2, 6, 4, 20, 19, 17, 18, 14, 13, 12, 15, 9, 10, 11, 1, 5, 21, 0]]
[[16, 8, 7, 3, 2, 6, 4, 20, 19, 17, 18, 14, 13, 12, 15, 9, 10, 11, 1, 5, 21, 0]]
tensor(True)
4
[[3, 2, 1, 6, 5, 4, 9, 8, 7, 0]]
最长路径边数: 9
[[3, 2, 1, 6, 5, 4, 9, 8, 7, 0]]
[[3, 2, 1, 6, 5, 4, 9, 8, 7, 0]]
tensor(True)
5
[[20, 15, 8, 7, 3, 2, 6, 4, 19, 18, 16, 17, 13, 12, 14, 9, 10, 11, 1, 5, 0]]
最长路径边数: 20
[[20, 15, 8, 7, 3, 2, 6, 4, 19, 18, 16, 17, 13, 12, 14, 9, 10, 11, 1, 5, 0]]
[[20, 15, 8, 7, 3, 2, 6, 4, 19, 18, 16, 17, 13, 12, 14, 9, 10, 11, 1, 5, 0]]
tensor(True)
6
[[50], [56], [60], [59], [58], [55], [57], [53], [54], [52], [6, 3, 1, 4, 5, 2, 14, 17, 16, 15, 12, 13, 19, 24, 23, 29, 28, 30, 27, 33, 31, 32, 26, 25, 22, 18, 20, 41, 40, 44, 43, 42, 38, 51, 49, 48, 47, 45, 46, 39, 35, 34, 36, 37, 21, 11, 10, 9, 8, 7, 0]]
最长路径边数: 54
[[50], [56], [60], [59], [58], [55], [57], [53], [54], [52], [6, 3, 1, 4, 5, 2, 14, 17, 16, 15, 12, 13, 19, 24, 23, 29, 28, 30, 27, 33, 31, 32, 26, 25, 22, 18, 20, 41, 40, 44, 43, 42, 38, 51, 49, 48, 47, 45, 46, 39, 35, 34, 36, 37, 21, 11, 10, 9, 8, 7, 0]]
[[50], [56], [60], [59], [58], [55], [57], [53], [54], [52], [6, 3, 1, 4, 5, 2, 14, 17, 16, 15, 12, 13, 19, 24, 23, 29, 28, 30, 27, 33, 31, 32, 26, 25, 22, 18, 20, 41, 40, 44, 43, 42, 38, 51, 49, 48, 47, 45, 46, 39, 35, 34, 36, 37, 21, 11, 10, 9, 8, 7, 0]]
tensor(False)
7
[[1, 9, 13, 12, 11, 10, 8, 7, 6, 5, 4, 3, 2, 0]]
最长路径边数: 13
[[1, 9, 13, 12, 11, 10, 8, 7, 6, 5, 4, 3, 2, 0]]
[[1, 9, 13, 12, 11, 10, 8, 7, 6, 5, 4, 3, 2, 0]]
tensor(True)
8
[[1, 5, 4, 13, 12, 17, 16, 15, 14, 10, 11, 2, 8, 9, 7, 6, 3, 0]]
最长路径边数: 17
[[1, 5, 4, 13, 12, 17, 16, 15, 14, 10, 11, 2, 8, 9, 7, 6, 3, 0]]
[[1, 5, 4, 13, 12, 17, 16, 15, 14, 10, 11, 2, 8, 9, 7, 6, 3, 0]]
tensor(True)
9
[[22], [21], [20], [19], [17, 15, 16, 18], [14], [13], [11], [4, 9, 6, 5, 3, 2, 0, 12, 10, 8, 7, 1]]
最长路径边数: 21
[[22], [21], [20], [19], [17, 15, 16, 18], [14], [13], [11], [4, 9, 6, 5, 3, 2, 0, 12, 10, 8, 7, 1]]
[[22], [21], [20], [19], [17, 15, 16, 18], [14], [13], [11], [4, 9, 6, 5, 3, 2, 0, 12, 10, 8, 7, 1]]
tensor(False)
10
[[19], [14, 5, 6, 8, 7, 12, 11, 10, 9, 2, 17, 18, 15, 1, 0, 16, 13, 4, 3]]
最长路径边数: 19
[[19], [14, 5, 6, 8, 7, 12, 11, 10, 9, 2, 17, 18, 15, 1, 0, 16, 13, 4, 3]]
[[19], [14, 5, 6, 8, 7, 12, 11, 10, 9, 2, 17, 18, 15, 1, 0, 16, 13, 4, 3]]
tensor(True)
11
[[19], [14, 5, 6, 8, 7, 12, 11, 10, 9, 2, 18, 17, 15, 1, 0, 16, 13, 4, 3]]
最长路径边数: 19
[[19], [14, 5, 6, 8, 7, 12, 11, 10, 9, 2, 18, 17, 15, 1, 0, 16, 13, 4, 3]]
[[19], [14, 5, 6, 8, 7, 12, 11, 10, 9, 2, 18, 17, 15, 1, 0, 16, 13, 4, 3]]
tensor(True)
12
[[30], [2], [1], [0], [27], [10], [4, 6, 5, 29, 8, 12, 11, 7, 16, 15, 14, 13, 9, 20, 19, 24, 26, 28, 25, 23, 21, 22, 18, 17, 3]]
最长路径边数: 25
[[30], [2], [1], [0], [27], [10], [4, 6, 5, 29, 8, 12, 11, 7, 16, 15, 14, 13, 9, 20, 19, 24, 26, 28, 25, 23, 21, 22, 18, 17, 3]]
[[30], [2], [1], [0], [27], [10], [4, 6, 5, 29, 8, 12, 11, 7, 16, 15, 14, 13, 9, 20, 19, 24, 26, 28, 25, 23, 21, 22, 18, 17, 3]]
tensor(False)
13
[[24], [22], [20], [19], [1, 14, 8, 3, 2, 4, 23, 9, 21, 17, 16, 15, 7, 18, 6, 5, 0, 13, 12, 11, 10]]
最长路径边数: 21
[[24], [22], [20], [19], [1, 14, 8, 3, 2, 4, 23, 9, 21, 17, 16, 15, 7, 18, 6, 5, 0, 13, 12, 11, 10]]
[[24], [22], [20], [19], [1, 14, 8, 3, 2, 4, 23, 9, 21, 17, 16, 15, 7, 18, 6, 5, 0, 13, 12, 11, 10]]
tensor(False)
14
[[14], [15], [13], [12], [11], [2, 1, 3, 7, 16, 10, 8, 5, 6, 4, 0, 9]]
最长路径边数: 14
[[14], [15], [13], [12], [11], [2, 1, 3, 7, 16, 10, 8, 5, 6, 4, 0, 9]]
[[14], [15], [13], [12], [11], [2, 1, 3, 7, 16, 10, 8, 5, 6, 4, 0, 9]]
tensor(False)
15
[[14], [11, 1, 4, 12, 16, 15, 13, 10, 9, 8, 7, 6, 5, 0, 3, 2]]
最长路径边数: 16
[[14], [11, 1, 4, 12, 16, 15, 13, 10, 9, 8, 7, 6, 5, 0, 3, 2]]
[[14], [11, 1, 4, 12, 16, 15, 13, 10, 9, 8, 7, 6, 5, 0, 3, 2]]
tensor(True)
16
[[1, 5, 3, 2, 0, 4]]
最长路径边数: 5
[[1, 5, 3, 2, 0, 4]]
[[1, 5, 3, 2, 0, 4]]
tensor(True)
17
[[41], [7, 19, 36, 1, 27, 40, 29, 2, 30, 4, 3, 9, 22, 25, 24, 23, 21, 34, 33, 32, 31, 28, 20, 15, 17, 16, 14, 13, 12, 11, 10, 8, 39, 38, 35, 26, 18, 6, 5, 42, 0, 37]]
最长路径边数: 42
[[41], [7, 19, 36, 1, 27, 40, 29, 2, 30, 4, 3, 9, 22, 25, 24, 23, 21, 34, 33, 32, 31, 28, 20, 15, 17, 16, 14, 13, 12, 11, 10, 8, 39, 38, 35, 26, 18, 6, 5, 42, 0, 37]]
[[41], [7, 19, 36, 1, 27, 40, 29, 2, 30, 4, 3, 9, 22, 25, 24, 23, 21, 34, 33, 32, 31, 28, 20, 15, 17, 16, 14, 13, 12, 11, 10, 8, 39, 38, 35, 26, 18, 6, 5, 42, 0, 37]]
tensor(True)
18
[[1, 3, 0, 2]]
最长路径边数: 3
[[1, 3, 0, 2]]
[[1, 3, 0, 2]]
tensor(True)
19
[[3], [1], [0, 2]]
最长路径边数: 3
[[3], [1], [0, 2]]
[[3], [1], [0, 2]]
tensor(True)
20
[[12], [10], [8], [1, 6, 5, 4, 3, 2, 13, 11, 9, 7, 0]]
最长路径边数: 11
[[12], [10], [8], [1, 6, 5, 4, 3, 2, 13, 11, 9, 7, 0]]
[[12], [10], [8], [1, 6, 5, 4, 3, 2, 13, 11, 9, 7, 0]]
tensor(False)
21
[[4], [7], [5], [6], [3, 0, 2, 1]]
最长路径边数: 5
[[4], [7], [5], [6], [3, 0, 2, 1]]
[[4], [7], [5], [6], [3, 0, 2, 1]]
tensor(False)
22
[[1, 3, 2, 0]]
最长路径边数: 3
[[1, 3, 2, 0]]
[[1, 3, 2, 0]]
tensor(True)
23
[[1, 0]]
最长路径边数: 1
[[1, 0]]
[[1, 0]]
tensor(True)
24
[[1, 0]]
最长路径边数: 1
[[1, 0]]
[[1, 0]]
tensor(True)
25
[[10], [13], [7], [4, 8, 6, 5, 9, 3, 11, 12, 0, 2, 1]]
最长路径边数: 11
[[10], [13], [7], [4, 8, 6, 5, 9, 3, 11, 12, 0, 2, 1]]
[[10], [13], [7], [4, 8, 6, 5, 9, 3, 11, 12, 0, 2, 1]]
tensor(False)
26
[[21], [29], [28], [27], [26], [20], [18], [19], [17], [24], [25], [9], [5, 1, 6, 2, 10, 11, 13, 23, 22, 16, 15, 14, 12, 8, 7, 0, 4, 3]]
最长路径边数: 22
[[21], [29], [28], [27], [26], [20], [18], [19], [17], [24], [25], [9], [5, 1, 6, 2, 10, 11, 13, 23, 22, 16, 15, 14, 12, 8, 7, 0, 4, 3]]
[[21], [29], [28], [27], [26], [20], [18], [19], [17], [24], [25], [9], [5, 1, 6, 2, 10, 11, 13, 23, 22, 16, 15, 14, 12, 8, 7, 0, 4, 3]]
tensor(False)
27
[[1, 2, 0]]
最长路径边数: 2
[[1, 2, 0]]
[[1, 2, 0]]
tensor(True)
28
[[2], [1, 0]]
最长路径边数: 2
[[2], [1, 0]]
[[2], [1, 0]]
tensor(True)
29
[[1, 0]]
最长路径边数: 1
[[1, 0]]
[[1, 0]]
tensor(True)
30
[[7, 6, 5, 4, 1, 3, 2, 0]]
最长路径边数: 7
[[7, 6, 5, 4, 1, 3, 2, 0]]
[[7, 6, 5, 4, 1, 3, 2, 0]]
tensor(True)
31
[[1, 0]]
最长路径边数: 1
[[1, 0]]
[[1, 0]]
tensor(True)
32
[[2, 8, 6, 5, 4, 3, 1, 0, 7]]
最长路径边数: 8
[[2, 8, 6, 5, 4, 3, 1, 0, 7]]
[[2, 8, 6, 5, 4, 3, 1, 0, 7]]
tensor(True)
33
[[3, 1, 9, 10, 16, 15, 14, 13, 12, 11, 8, 7, 6, 5, 4, 2, 0]]
最长路径边数: 16
[[3, 1, 9, 10, 16, 15, 14, 13, 12, 11, 8, 7, 6, 5, 4, 2, 0]]
[[3, 1, 9, 10, 16, 15, 14, 13, 12, 11, 8, 7, 6, 5, 4, 2, 0]]
tensor(True)
34
[[5], [2, 1, 4, 0, 3]]
最长路径边数: 5
[[5], [2, 1, 4, 0, 3]]
[[5], [2, 1, 4, 0, 3]]
tensor(True)
35
[[3, 2, 1, 0]]
最长路径边数: 3
[[3, 2, 1, 0]]
[[3, 2, 1, 0]]
tensor(True)
36
[[1, 7, 6, 5, 4, 2, 8, 9, 3, 0]]
最长路径边数: 9
[[1, 7, 6, 5, 4, 2, 8, 9, 3, 0]]
[[1, 7, 6, 5, 4, 2, 8, 9, 3, 0]]
tensor(True)
37
[[4, 2, 3, 0, 1]]
最长路径边数: 4
[[4, 2, 3, 0, 1]]
[[4, 2, 3, 0, 1]]
tensor(True)
38
[[4, 30, 28, 6, 7, 5, 31, 10, 15, 14, 13, 12, 11, 9, 8, 22, 25, 24, 23, 21, 20, 35, 34, 33, 32, 18, 17, 19, 16, 2, 1, 0, 29, 27, 26, 3]]
最长路径边数: 35
[[4, 30, 28, 6, 7, 5, 31, 10, 15, 14, 13, 12, 11, 9, 8, 22, 25, 24, 23, 21, 20, 35, 34, 33, 32, 18, 17, 19, 16, 2, 1, 0, 29, 27, 26, 3]]
[[4, 30, 28, 6, 7, 5, 31, 10, 15, 14, 13, 12, 11, 9, 8, 22, 25, 24, 23, 21, 20, 35, 34, 33, 32, 18, 17, 19, 16, 2, 1, 0, 29, 27, 26, 3]]
tensor(True)
39
[[5], [4, 0, 3, 2, 1]]
最长路径边数: 5
[[5], [4, 0, 3, 2, 1]]
[[5], [4, 0, 3, 2, 1]]
tensor(True)
40
[[1, 0]]
最长路径边数: 1
[[1, 0]]
[[1, 0]]
tensor(True)
41
[[2], [1, 0]]
最长路径边数: 2
[[2], [1, 0]]
[[2], [1, 0]]
tensor(True)
42
[[3], [2], [1], [0]]
最长路径边数: 3
[[3], [2], [1], [0]]
[[3], [2], [1], [0]]
tensor(True)
43
[[24], [21, 20], [22], [11], [25, 1, 7, 4, 2, 3, 9, 23, 14, 18, 15, 13, 12, 8, 10, 6, 5, 19, 0, 17, 16]]
最长路径边数: 22
[[24], [21, 20], [22], [11], [25, 1, 7, 4, 2, 3, 9, 23, 14, 18, 15, 13, 12, 8, 10, 6, 5, 19, 0, 17, 16]]
[[24], [21, 20], [22], [11], [25, 1, 7, 4, 2, 3, 9, 23, 14, 18, 15, 13, 12, 8, 10, 6, 5, 19, 0, 17, 16]]
tensor(False)
44
[[21], [26], [18], [15], [29], [28], [5, 1, 6, 3, 4, 2, 19, 17, 22, 25, 24, 20, 27, 23, 14, 13, 12, 11, 9, 8, 7, 16, 30, 0, 10]]
最长路径边数: 26
[[21], [26], [18], [15], [29], [28], [5, 1, 6, 3, 4, 2, 19, 17, 22, 25, 24, 20, 27, 23, 14, 13, 12, 11, 9, 8, 7, 16, 30, 0, 10]]
[[21], [26], [18], [15], [29], [28], [5, 1, 6, 3, 4, 2, 19, 17, 22, 25, 24, 20, 27, 23, 14, 13, 12, 11, 9, 8, 7, 16, 30, 0, 10]]
tensor(False)
45
[[4], [1, 3, 2, 0]]
最长路径边数: 4
[[4], [1, 3, 2, 0]]
[[4], [1, 3, 2, 0]]
tensor(True)
46
[[9], [1, 5, 4, 8, 7, 6, 3, 2, 0]]
最长路径边数: 9
[[9], [1, 5, 4, 8, 7, 6, 3, 2, 0]]
[[9], [1, 5, 4, 8, 7, 6, 3, 2, 0]]
tensor(True)
47
[[26], [7, 2, 13, 1, 10, 16, 14, 9, 11, 8, 20, 19, 18, 33, 32, 31, 30, 25, 24, 23, 29, 28, 27, 22, 21, 17, 15, 12, 4, 6, 5, 3, 0]]
最长路径边数: 33
[[26], [7, 2, 13, 1, 10, 16, 14, 9, 11, 8, 20, 19, 18, 33, 32, 31, 30, 25, 24, 23, 29, 28, 27, 22, 21, 17, 15, 12, 4, 6, 5, 3, 0]]
[[26], [7, 2, 13, 1, 10, 16, 14, 9, 11, 8, 20, 19, 18, 33, 32, 31, 30, 25, 24, 23, 29, 28, 27, 22, 21, 17, 15, 12, 4, 6, 5, 3, 0]]
tensor(True)
48
[[2, 1, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 26, 16, 15, 3, 7, 0]]
最长路径边数: 27
[[2, 1, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 26, 16, 15, 3, 7, 0]]
[[2, 1, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 26, 16, 15, 3, 7, 0]]
tensor(True)
49
[[11], [1, 13, 6, 14, 7, 2, 12, 9, 8, 5, 17, 16, 15, 4, 0, 10, 3]]
最长路径边数: 17
[[11], [1, 13, 6, 14, 7, 2, 12, 9, 8, 5, 17, 16, 15, 4, 0, 10, 3]]
[[11], [1, 13, 6, 14, 7, 2, 12, 9, 8, 5, 17, 16, 15, 4, 0, 10, 3]]
tensor(True)
50
[[13], [10], [6, 5, 4, 3, 16, 2, 7, 8, 18, 17, 15, 12, 11, 9, 14, 0, 1]]
最长路径边数: 17
[[13], [10], [6, 5, 4, 3, 16, 2, 7, 8, 18, 17, 15, 12, 11, 9, 14, 0, 1]]
[[13], [10], [6, 5, 4, 3, 16, 2, 7, 8, 18, 17, 15, 12, 11, 9, 14, 0, 1]]
tensor(False)
51
[[1, 13, 14, 3, 2, 6, 5, 4, 11, 10, 9, 8, 7, 0, 12]]
最长路径边数: 14
[[1, 13, 14, 3, 2, 6, 5, 4, 11, 10, 9, 8, 7, 0, 12]]
[[1, 13, 14, 3, 2, 6, 5, 4, 11, 10, 9, 8, 7, 0, 12]]
tensor(True)
52
[[12, 17, 16, 15, 14, 13, 11, 10, 9, 8, 7, 6, 5, 4, 0, 3, 2, 1]]
最长路径边数: 17
[[12, 17, 16, 15, 14, 13, 11, 10, 9, 8, 7, 6, 5, 4, 0, 3, 2, 1]]
[[12, 17, 16, 15, 14, 13, 11, 10, 9, 8, 7, 6, 5, 4, 0, 3, 2, 1]]
tensor(True)
53
[[18], [19], [2, 20, 21, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 1, 0]]
最长路径边数: 20
[[18], [19], [2, 20, 21, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 1, 0]]
[[18], [19], [2, 20, 21, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 1, 0]]
tensor(False)
54
[[1, 10, 11, 6, 15, 14, 13, 12, 5, 4, 16, 2, 0, 9, 8, 7, 3]]
最长路径边数: 16
[[1, 10, 11, 6, 15, 14, 13, 12, 5, 4, 16, 2, 0, 9, 8, 7, 3]]
[[1, 10, 11, 6, 15, 14, 13, 12, 5, 4, 16, 2, 0, 9, 8, 7, 3]]
tensor(True)
55
[[21], [18], [15], [1, 5, 2, 3, 9, 7, 13, 10, 11, 8, 6, 12, 25, 26, 17, 16, 24, 20, 19, 23, 22, 14, 0, 4]]
最长路径边数: 24
[[21], [18], [15], [1, 5, 2, 3, 9, 7, 13, 10, 11, 8, 6, 12, 25, 26, 17, 16, 24, 20, 19, 23, 22, 14, 0, 4]]
[[21], [18], [15], [1, 5, 2, 3, 9, 7, 13, 10, 11, 8, 6, 12, 25, 26, 17, 16, 24, 20, 19, 23, 22, 14, 0, 4]]
tensor(False)
56
[[4], [2, 5, 8, 7, 3, 1, 12, 11, 10, 9, 6, 0]]
最长路径边数: 12
[[4], [2, 5, 8, 7, 3, 1, 12, 11, 10, 9, 6, 0]]
[[4], [2, 5, 8, 7, 3, 1, 12, 11, 10, 9, 6, 0]]
tensor(True)
57
[[23], [27], [20], [14], [2, 1, 8, 7, 6, 5, 16, 32, 22, 25, 26, 24, 21, 31, 28, 29, 30, 19, 17, 18, 15, 9, 12, 10, 11, 4, 3, 0, 13]]
最长路径边数: 29
[[23], [27], [20], [14], [2, 1, 8, 7, 6, 5, 16, 32, 22, 25, 26, 24, 21, 31, 28, 29, 30, 19, 17, 18, 15, 9, 12, 10, 11, 4, 3, 0, 13]]
[[23], [27], [20], [14], [2, 1, 8, 7, 6, 5, 16, 32, 22, 25, 26, 24, 21, 31, 28, 29, 30, 19, 17, 18, 15, 9, 12, 10, 11, 4, 3, 0, 13]]
tensor(False)
58
[[3], [1, 2, 0]]
最长路径边数: 3
[[3], [1, 2, 0]]
[[3], [1, 2, 0]]
tensor(True)
59
[[1, 2, 3, 0]]
最长路径边数: 3
[[1, 2, 3, 0]]
[[1, 2, 3, 0]]
tensor(True)
60
[[14], [13, 12], [11], [4, 5, 3, 6, 1, 7, 9, 10, 8, 2, 0]]
最长路径边数: 13
[[14], [13, 12], [11], [4, 5, 3, 6, 1, 7, 9, 10, 8, 2, 0]]
[[14], [13, 12], [11], [4, 5, 3, 6, 1, 7, 9, 10, 8, 2, 0]]
tensor(False)
61
[[6, 7], [10], [14, 15], [11, 12], [13], [16, 1, 2, 3, 9, 4, 0, 8]]
最长路径边数: 11
[[6, 7], [10], [14, 15], [11, 12], [13], [16, 1, 2, 3, 9, 4, 0, 8]]
[[6, 7], [10], [14, 15], [11, 12], [13], [16, 1, 2, 3, 9, 4, 0, 8]]
tensor(False)
62
[[3], [2, 1, 0]]
最长路径边数: 3
[[3], [2, 1, 0]]
[[3], [2, 1, 0]]
tensor(True)
63
[[7], [1, 9, 3, 8, 6, 5, 2, 4, 0]]
最长路径边数: 9
[[7], [1, 9, 3, 8, 6, 5, 2, 4, 0]]
[[7], [1, 9, 3, 8, 6, 5, 2, 4, 0]]
tensor(True)
64
[[2, 1, 3, 7, 15, 14, 13, 12, 11, 10, 9, 8, 6, 5, 17, 4, 18, 16, 0]]
最长路径边数: 18
[[2, 1, 3, 7, 15, 14, 13, 12, 11, 10, 9, 8, 6, 5, 17, 4, 18, 16, 0]]
[[2, 1, 3, 7, 15, 14, 13, 12, 11, 10, 9, 8, 6, 5, 17, 4, 18, 16, 0]]
tensor(True)
65
[[9], [8], [7], [2, 3, 1, 0, 6, 5, 4]]
最长路径边数: 9
[[9], [8], [7], [2, 3, 1, 0, 6, 5, 4]]
[[9], [8], [7], [2, 3, 1, 0, 6, 5, 4]]
tensor(True)
66
[[2], [0, 1]]
最长路径边数: 2
[[2], [0, 1]]
[[2], [0, 1]]
tensor(True)
67
[[6, 5, 3, 4, 7, 8, 0, 2, 1]]
最长路径边数: 8
[[6, 5, 3, 4, 7, 8, 0, 2, 1]]
[[6, 5, 3, 4, 7, 8, 0, 2, 1]]
tensor(True)
68
[[5], [2, 3, 1, 0, 4]]
最长路径边数: 5
[[5], [2, 3, 1, 0, 4]]
[[5], [2, 3, 1, 0, 4]]
tensor(True)
69
[[18], [19], [30], [21], [27], [22], [14], [11], [24], [15], [28], [31], [33], [25], [10], [3], [2, 1, 4, 9, 35, 34, 8, 7, 20, 29, 13, 12, 26, 39, 38, 32, 23, 17, 16, 37, 36, 6, 5, 0]]
最长路径边数: 24
[[18], [19], [30], [21], [27], [22], [14], [11], [24], [15], [28], [31], [33], [25], [10], [3], [2, 1, 4, 9, 35, 34, 8, 7, 20, 29, 13, 12, 26, 39, 38, 32, 23, 17, 16, 37, 36, 6, 5, 0]]
[[18], [19], [30], [21], [27], [22], [14], [11], [24], [15], [28], [31], [33], [25], [10], [3], [2, 1, 4, 9, 35, 34, 8, 7, 20, 29, 13, 12, 26, 39, 38, 32, 23, 17, 16, 37, 36, 6, 5, 0]]
tensor(False)
70
[[22], [17], [23], [21], [2, 5, 4, 1, 8, 6, 11, 10, 3, 16, 14, 13, 24, 19, 18, 20, 15, 12, 7, 0, 9]]
最长路径边数: 22
[[22], [17], [23], [21], [2, 5, 4, 1, 8, 6, 11, 10, 3, 16, 14, 13, 24, 19, 18, 20, 15, 12, 7, 0, 9]]
[[22], [17], [23], [21], [2, 5, 4, 1, 8, 6, 11, 10, 3, 16, 14, 13, 24, 19, 18, 20, 15, 12, 7, 0, 9]]
tensor(False)
71
[[17], [19], [1, 2, 4, 3, 8, 12, 18, 16, 15, 14, 13, 11, 10, 9, 7, 6, 5, 0]]
最长路径边数: 18
[[17], [19], [1, 2, 4, 3, 8, 12, 18, 16, 15, 14, 13, 11, 10, 9, 7, 6, 5, 0]]
[[17], [19], [1, 2, 4, 3, 8, 12, 18, 16, 15, 14, 13, 11, 10, 9, 7, 6, 5, 0]]
tensor(False)
72
[[27], [30], [24], [31], [25], [28], [26], [29], [13], [33], [19], [12], [32], [16, 17, 15], [7, 4, 10, 18, 14, 11, 9, 8, 5, 3, 2, 1, 6, 20, 21, 0], [22, 23]]
最长路径边数: 19
[[27], [30], [24], [31], [25], [28], [26], [29], [13], [33], [19], [12], [32], [16, 17, 15], [7, 4, 10, 18, 14, 11, 9, 8, 5, 3, 2, 1, 6, 20, 21, 0], [22, 23]]
[[27], [30], [24], [31], [25], [28], [26], [29], [13], [33], [19], [12], [32], [16, 17, 15], [7, 4, 10, 18, 14, 11, 9, 8, 5, 3, 2, 1, 6, 20, 21, 0], [22, 23]]
tensor(False)
73
[[31], [33], [16], [12], [13], [1, 3, 2, 7, 9, 8, 5, 4, 14, 15, 22, 21, 18, 17, 11, 10, 6, 28, 27, 26, 32, 30, 29, 25, 24, 23, 20, 19, 0]]
最长路径边数: 29
[[31], [33], [16], [12], [13], [1, 3, 2, 7, 9, 8, 5, 4, 14, 15, 22, 21, 18, 17, 11, 10, 6, 28, 27, 26, 32, 30, 29, 25, 24, 23, 20, 19, 0]]
[[31], [33], [16], [12], [13], [1, 3, 2, 7, 9, 8, 5, 4, 14, 15, 22, 21, 18, 17, 11, 10, 6, 28, 27, 26, 32, 30, 29, 25, 24, 23, 20, 19, 0]]
tensor(False)
74
[[34], [33], [32], [31], [30], [15], [1, 11, 5, 4, 3, 2, 8, 9, 7, 6, 16, 24, 18, 25, 29, 28, 27, 26, 23, 22, 21, 20, 19, 17, 14, 13, 12, 0, 10]]
最长路径边数: 31
[[34], [33], [32], [31], [30], [15], [1, 11, 5, 4, 3, 2, 8, 9, 7, 6, 16, 24, 18, 25, 29, 28, 27, 26, 23, 22, 21, 20, 19, 17, 14, 13, 12, 0, 10]]
[[34], [33], [32], [31], [30], [15], [1, 11, 5, 4, 3, 2, 8, 9, 7, 6, 16, 24, 18, 25, 29, 28, 27, 26, 23, 22, 21, 20, 19, 17, 14, 13, 12, 0, 10]]
tensor(False)
75
[[9, 3, 10, 11, 1, 5, 4, 2, 13, 7, 6, 15, 14, 8, 12, 0]]
最长路径边数: 15
[[9, 3, 10, 11, 1, 5, 4, 2, 13, 7, 6, 15, 14, 8, 12, 0]]
[[9, 3, 10, 11, 1, 5, 4, 2, 13, 7, 6, 15, 14, 8, 12, 0]]
tensor(True)
76
[[1, 0]]
最长路径边数: 1
[[1, 0]]
[[1, 0]]
tensor(True)
77
[[15], [5], [4, 1, 7, 11, 12, 10, 6, 2, 13, 9, 0, 14, 8, 3]]
最长路径边数: 14
[[15], [5], [4, 1, 7, 11, 12, 10, 6, 2, 13, 9, 0, 14, 8, 3]]
[[15], [5], [4, 1, 7, 11, 12, 10, 6, 2, 13, 9, 0, 14, 8, 3]]
tensor(False)
78
[[1, 2, 0]]
最长路径边数: 2
[[1, 2, 0]]
[[1, 2, 0]]
tensor(True)
79
[[1, 6, 5, 3, 2, 4, 0]]
最长路径边数: 6
[[1, 6, 5, 3, 2, 4, 0]]
[[1, 6, 5, 3, 2, 4, 0]]
tensor(True)
80
[[1, 3, 5, 4, 8, 7, 6, 2, 0]]
最长路径边数: 8
[[1, 3, 5, 4, 8, 7, 6, 2, 0]]
[[1, 3, 5, 4, 8, 7, 6, 2, 0]]
tensor(True)
81
[[1, 0]]
最长路径边数: 1
[[1, 0]]
[[1, 0]]
tensor(True)
82
[[1, 0]]
最长路径边数: 1
[[1, 0]]
[[1, 0]]
tensor(True)
83
[[14, 13], [12], [11], [15], [10], [9], [8, 7], [6], [5, 4], [3], [2], [1, 0]]
最长路径边数: 12
[[14, 13], [12], [11], [15], [10], [9], [8, 7], [6], [5, 4], [3], [2], [1, 0]]
[[14, 13], [12], [11], [15], [10], [9], [8, 7], [6], [5, 4], [3], [2], [1, 0]]
tensor(False)
84
[[2, 1, 4, 6, 3, 5, 0]]
最长路径边数: 6
[[2, 1, 4, 6, 3, 5, 0]]
[[2, 1, 4, 6, 3, 5, 0]]
tensor(True)
85
[[3, 1, 0, 2]]
最长路径边数: 3
[[3, 1, 0, 2]]
[[3, 1, 0, 2]]
tensor(True)
86
[[21, 20, 19, 18, 17, 2, 10, 0, 3, 1], [4, 9, 8, 7, 6, 5], [16, 15, 14, 13, 12, 11]]
最长路径边数: 9
[[21, 20, 19, 18, 17, 2, 10, 0, 3, 1], [4, 9, 8, 7, 6, 5], [16, 15, 14, 13, 12, 11]]
[[21, 20, 19, 18, 17, 2, 10, 0, 3, 1], [4, 9, 8, 7, 6, 5], [16, 15, 14, 13, 12, 11]]
tensor(False)
87
[[11, 1, 18, 16, 0, 17, 15, 14, 13, 12, 10, 9, 8, 7, 6, 5, 4, 3, 2]]
最长路径边数: 18
[[11, 1, 18, 16, 0, 17, 15, 14, 13, 12, 10, 9, 8, 7, 6, 5, 4, 3, 2]]
[[11, 1, 18, 16, 0, 17, 15, 14, 13, 12, 10, 9, 8, 7, 6, 5, 4, 3, 2]]
tensor(True)
88
[[2, 7, 6, 5, 4, 3], [0, 1]]
最长路径边数: 5
[[2, 7, 6, 5, 4, 3], [0, 1]]
[[2, 7, 6, 5, 4, 3], [0, 1]]
tensor(False)
89
[[10, 11, 12, 14, 3, 5, 7, 6, 4, 0, 17, 16, 15, 13, 9, 8, 2, 1]]
最长路径边数: 17
[[10, 11, 12, 14, 3, 5, 7, 6, 4, 0, 17, 16, 15, 13, 9, 8, 2, 1]]
[[10, 11, 12, 14, 3, 5, 7, 6, 4, 0, 17, 16, 15, 13, 9, 8, 2, 1]]
tensor(True)
90
[[24], [23], [14, 17, 16, 6, 22, 19, 20, 8, 7, 0, 21, 18, 15, 13, 12, 11, 10, 9, 5, 4, 3, 2, 1]]
最长路径边数: 24
[[24], [23], [14, 17, 16, 6, 22, 19, 20, 8, 7, 0, 21, 18, 15, 13, 12, 11, 10, 9, 5, 4, 3, 2, 1]]
[[24], [23], [14, 17, 16, 6, 22, 19, 20, 8, 7, 0, 21, 18, 15, 13, 12, 11, 10, 9, 5, 4, 3, 2, 1]]
tensor(True)
91
[[1, 5, 4, 10, 9, 0, 11, 8, 7, 6, 3, 2]]
最长路径边数: 11
[[1, 5, 4, 10, 9, 0, 11, 8, 7, 6, 3, 2]]
[[1, 5, 4, 10, 9, 0, 11, 8, 7, 6, 3, 2]]
tensor(True)
92
[[15, 2, 19, 18, 17, 16, 0, 3, 1], [11, 12, 4, 14, 13, 10, 9, 8, 7, 6, 5]]
最长路径边数: 10
[[15, 2, 19, 18, 17, 16, 0, 3, 1], [11, 12, 4, 14, 13, 10, 9, 8, 7, 6, 5]]
[[15, 2, 19, 18, 17, 16, 0, 3, 1], [11, 12, 4, 14, 13, 10, 9, 8, 7, 6, 5]]
tensor(False)
93
[[3, 0, 2, 1]]
最长路径边数: 3
[[3, 0, 2, 1]]
[[3, 0, 2, 1]]
tensor(True)
94
[[3, 0, 2, 1]]
最长路径边数: 3
[[3, 0, 2, 1]]
[[3, 0, 2, 1]]
tensor(True)
95
[[1, 2, 5, 0, 6, 4, 3]]
最长路径边数: 6
[[1, 2, 5, 0, 6, 4, 3]]
[[1, 2, 5, 0, 6, 4, 3]]
tensor(True)
96
[[1, 2, 5, 0, 6, 4, 3]]
最长路径边数: 6
[[1, 2, 5, 0, 6, 4, 3]]
[[1, 2, 5, 0, 6, 4, 3]]
tensor(True)
97
[[2, 0, 5, 4, 3, 1]]
最长路径边数: 5
[[2, 0, 5, 4, 3, 1]]
[[2, 0, 5, 4, 3, 1]]
tensor(True)
98
[[2, 0, 5, 4, 3, 1]]
最长路径边数: 5
[[2, 0, 5, 4, 3, 1]]
[[2, 0, 5, 4, 3, 1]]
tensor(True)
99
[[2, 0, 5, 4, 3, 1]]
最长路径边数: 5
[[2, 0, 5, 4, 3, 1]]
[[2, 0, 5, 4, 3, 1]]
tensor(True)
100
[[2, 0, 5, 4, 3, 1]]
最长路径边数: 5
[[2, 0, 5, 4, 3, 1]]
[[2, 0, 5, 4, 3, 1]]
tensor(True)
101
[[18], [4, 1, 3, 5, 2, 12, 9, 8, 6, 7, 15, 17, 16, 19, 20, 14, 13, 0, 21, 11, 10]]
最长路径边数: 21

In [116]:
paths

[34,
 4,
 7,
 21,
 9,
 20,
 54,
 13,
 17,
 21,
 19,
 19,
 25,
 21,
 14,
 16,
 5,
 42,
 3,
 3,
 11,
 5,
 3,
 1,
 1,
 11,
 22,
 2,
 2,
 1,
 7,
 1,
 8,
 16,
 5,
 3,
 9,
 4,
 35,
 5,
 1,
 2,
 3,
 22,
 26,
 4,
 9,
 33,
 27,
 17,
 17,
 14,
 17,
 20,
 16,
 24,
 12,
 29,
 3,
 3,
 13,
 11,
 3,
 9,
 18,
 9,
 2,
 8,
 5,
 24,
 22,
 18,
 19,
 29,
 31,
 15,
 1,
 14,
 2,
 6,
 8,
 1,
 1,
 12,
 6,
 3,
 9,
 18,
 5,
 17,
 24,
 11,
 10,
 3,
 3,
 6,
 6,
 5,
 5,
 5,
 5,
 21,
 1,
 1,
 1,
 8,
 4,
 13,
 8,
 17,
 11,
 2,
 7,
 14,
 8,
 23,
 5,
 4,
 28,
 15,
 16,
 22,
 12,
 14,
 14,
 13,
 23,
 16,
 8,
 27,
 14,
 7,
 7,
 7,
 14,
 21,
 7,
 33,
 9,
 11,
 36,
 9,
 13,
 11,
 17,
 9,
 8,
 11,
 10,
 16,
 1,
 30,
 20,
 3,
 20,
 17,
 33,
 10,
 5,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 4,
 1,
 30,
 30,
 19,
 11,
 19,
 23,
 16,
 22,
 35,
 14,
 31,
 7,
 6,
 29,
 10,
 8,
 17,
 6,
 6,
 9,
 9,
 9,
 2,
 3,
 2,
 2,
 13,
 11,
 4,
 4,
 28,
 1,
 16,
 1,
 1,
 1,
 1,
 9,
 11,
 12,
 6,
 4,
 1,
 4,
 2,
 5,
 14,
 31,
 3,
 2,
 10,
 15,
 2,
 6,
 20,
 10,
 10,
 14,
 18,
 23,
 20,
 19,
 22,
 16,
 4,
 5,
 25,
 48,
 10,
 8,
 36,
 6,
 14,
 11,
 8,
 11,
 6,
 6,
 6,
 6,
 6,
 7,
 6,
 6,
 7,
 6,
 10,
 10,
 6,
 12,
 10,
 12,
 12,
 12,
 19,
 12,
 13,
 14,
 14,
 12,
 12,
 12,
 15,
 19,
 15,
 12,
 12,
 3,
 18,
 6,
 8,
 13,
 9,
 12,
 12,
 12,
 12,
 12,
 12,
 1,
 19,
 10,
 5,
 4,
 10,
 5,
 1,
 1,
 6,
 3,
 3,
 1,
 12,
 19,
 31,
 12,
 12,
 28,
 38,
 4,
 3,
 3,
 1,
 3,
 2,
 1,
 7,
 9,
 6,
 4,
 14,
 13,
 12,
 9,
 11,
 12,
 14,
 1,
 5,
 3,
 3,
 3,
 2,
 1,
 1,
 12,
 10,
 6,
 15,
 8,
 4,
 10,
 2,
 3,
 8,
 1,
 5,
 19,
 7,
 12,
 12,
 17,
 12,
 39,
 28,
 8,
 8,
 5,
 5,
 5,
 17,
 11,
 12,
 9,
 13,
 26,
 22,
 16,
 17,
 8,
 8,
 3,
 4,
 5,
 5,
 7,
 4,
 4,
 4,
 5,
 11,
 16,
 13,
 10,
 11,
 15,
 39,
 23,
 24,
 2,
 4,
 8,
 18,
 2,
 8,
 10,
 1,
 1,
 3,
 1,
 3,
 1,
 28,
 3,
 6,
 12,
 2,
 4,
 3,
 2,
 5,
 4,
 3,
 2,
 2,
 1,
 1,
 14,
 1,
 6,
 1,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 11,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 13,
 29,
 5,
 4,
 5,
 4,
 4,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 31,
 3,
 8,
 32,
 33,
 29,
 29,
 27,
 27,
 33,
 3,
 1,
 3,
 20,
 13,
 36,
 20,
 36,
 21,
 20,
 16,
 18,
 2,
 1,
 31,
 2,
 2,
 14,
 12,
 16,
 11,
 14,
 10,
 9,
 19,
 13,
 31,
 9,
 7,
 6,
 1,
 1,
 1,
 6,
 7,
 4,
 14,
 16,
 32,
 15,
 10,
 10,
 14,
 18,
 18,
 12,
 27,
 9,
 39,
 12,
 14,
 22,
 8,
 1,
 10,
 9,
 9,
 10,
 1,
 3,
 19,
 15,
 1,
 7,
 2,
 1,
 5,
 1,
 26,
 3,
 4,
 1,
 1,
 1,
 2,
 1,
 4,
 4,
 4,
 8,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 1,
 1,
 1,
 4,
 14,
 7,
 6,
 29,
 1,
 1,
 4,
 1,
 3,
 5,
 7,
 7,
 5,
 5,
 5,
 2,
 8,
 8,
 6,
 8,
 8,
 17,
 6,
 2,
 15,
 9,
 7,
 1,
 4,
 2,
 4,
 8,
 15,
 5,
 3,
 6,
 10,
 6,
 4,
 12,
 8,
 1,
 5,
 16,
 7,
 12,
 7,
 6,
 2,
 7,
 23,
 5,
 26,
 24,
 7,
 7,
 11,
 6,
 6,
 12,
 3,
 18,
 15,
 2,
 15,
 4,
 22,
 2,
 3,
 20,
 4,
 3,
 12,
 28,
 12,
 20,
 3,
 3,
 10,
 10,
 8,
 4,
 10,
 23,
 16,
 4,
 12,
 6,
 8,
 4,
 4,
 4,
 8,
 8,
 1,
 8,
 8,
 14,
 8,
 10,
 5,
 15,
 14,
 28,
 3,
 7,
 21,
 2,
 1,
 1,
 4,
 5,
 2,
 3,
 6,
 15,
 3,
 2,
 4,
 3,
 6,
 2,
 1,
 21,
 22,
 27,
 13,
 2,
 10,
 11,
 12,
 16,
 11,
 15,
 13,
 38,
 6,
 4,
 12,
 21,
 19,
 19,
 14,
 12,
 24,
 18,
 4,
 15,
 13,
 8,
 9,
 9,
 6,
 2,
 8,
 13,
 14,
 6,
 8,
 6,
 21,
 11,
 5,
 13,
 40,
 12,
 10,
 1,
 4,
 11,
 17,
 12,
 10,
 5,
 5,
 5,
 6,
 6,
 6,
 9,
 26,
 10,
 9,
 18,
 9,
 20,
 40,
 9,
 7,
 9,
 10,
 5,
 14,
 50,
 13,
 9,
 35,
 1,
 26,
 8,
 27,
 11,
 26,
 5,
 10,
 21,
 36,
 1,
 6,
 6,
 5,
 1,
 1,
 26,
 17,
 18,
 2,
 2,
 1,
 1,
 1,
 1,
 25,
 12,
 1,
 3,
 2,
 2,
 2,
 2,
 1,
 6,
 4,
 5,
 28,
 8,
 8,
 20,
 2,
 3,
 19,
 2,
 57,
 15,
 1,
 10,
 3,
 28,
 27,
 13,
 17,
 4,
 3,
 30,
 3,
 11,
 8,
 7,
 35,
 11,
 17,
 1,
 1,
 1,
 1,
 19,
 20,
 38,
 19,
 6,
 17,
 10,
 27,
 10,
 11,
 22,
 5,
 40,
 2,
 15,
 11,
 11,
 17,
 27,
 21,
 6,
 9,
 26,
 12,
 6,
 7,
 4,
 3,
 2,
 4,
 3,
 4,
 6,
 6,
 9,
 6,
 9,
 9,
 2,
 6,
 6,
 9,
 9,
 4,
 4,
 2,
 6,
 6,
 9,
 6,
 4,
 1,
 3,
 3,
 1,
 1,
 3,
 1,
 8,
 3,
 2,
 2,
 8,
 5,
 7,
 2,
 2,
 3,
 2,
 7,
 7,
 2,
 7,
 2,
 4,
 1,
 6,
 5,
 3,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 7,
 8,
 4,
 7,
 1,
 5,
 20,
 3,
 5,
 6,
 7,
 1,
 6,
 6,
 6,
 4,
 5,
 1,
 3,
 4,
 7,
 2,
 6,
 3,
 5,
 24,
 5,
 24,
 1,
 10,
 11,
 9,
 1,
 2,
 2,
 5,
 4,
 2,
 3,
 4,
 4,
 4,
 4,
 4,
 1,
 49,
 8,
 36,
 1,
 10,
 16,
 1,
 13,
 8,
 7,
 10,
 5,
 6,
 4,
 17,
 16,
 3,
 3,
 6,
 7,
 3,
 12,
 7,
 5,
 8,
 26,
 30,
 14,
 36,
 6,
 18,
 11,
 ...]

In [1]:
import pandas as pd
df = pd.read_pickle("/root/autodl-tmp/vul-detect/utils/data/torch_geometrics_process/cfexplainer/storage/processed/CVEfixes/None_processed/CVEfixes_dataframe_ncode.pkl")
df.head()

,idx,cve_id,func,target,programming_language,id,valid,torch_geometrics_data
0,0,CVE-2010-10006,public Authentication getAuthentication(Ht...,1,Java,4,True,"[[(x, tensor([[ 0.0157, 0.0055, -0.0043, ......"
1,1,CVE-2010-3260,public SAXParser newSAXParser() throws Par...,1,Java,7,True,"[[(x, tensor([[ 0.0157, 0.0055, -0.0043, ......"
2,2,CVE-2010-5327,\tpublic void fireUndeployEvent(HotDeployEvent...,1,Java,10,True,"[[(x, tensor([[ 0.0157, 0.0055, -0.0043, ......"
3,3,CVE-2010-5327,\tpublic Template getTemplate(\n\t\tString tem...,1,Java,14,True,"[[(x, tensor([[ 0.0157, 0.0055, -0.0043, ......"
4,4,CVE-2010-5327,"\tpublic Map<String, Object> getHelperUtilitie...",1,Java,17,True,"[[(x, tensor([[ 0.0157, 0.0055, -0.0043, ......"

In [2]:
df.shape

(13487, 8)

In [3]:
new_df = pd.read_json("/root/autodl-tmp/vul-detect/data/raw/CVEfixes/new_dataset_2.json")
new_df.head()

,cve_id,func,target,programming_language,token
0,CWE-119,static __u8 *kye_report_fixup(struct hid_devic...,1,Java,294
1,CWE-119,static __u8 *kye_report_fixup(struct hid_devic...,0,Java,294
2,CWE-330,"void add_interrupt_randomness(int irq, int irq...",0,Java,384
3,CWE-208,public Authentication getAuthentication(Ht...,0,Java,331
4,CWE-208,public Authentication getAuthentication(Ht...,1,Java,331

In [4]:
new_df.shape

(33020, 5)

In [5]:
df['cve_id'] = df['id'].map(new_df['cve_id'])

In [6]:
df.shape

(13487, 8)

In [7]:
df.to_pickle("/root/autodl-tmp/vul-detect/utils/data/torch_geometrics_process/cfexplainer/storage/processed/CVEfixes/None_processed/CVEfixes_dataframe_ncode_2.pkl")