已连接到 vul-detect (Python 3.9.21)

In [1]:
import dgl
import pandas as pd

In [2]:
data = pd.read_pickle("/root/autodl-tmp/naturalcc/examples/counterfactual-vulnerability-detection/cfexplainer/storage/processed/vul_graph_dataset/train_processed/dataframe.pkl")


data.head()

,idx,dataset,id,label,removed,added,diff,before,after,vul,valid,torch_geometrics_data
0,0,bigvul,177808,train,[],"[42, 43]",zset_outputintent(i_ctx_t * i_ctx_p)\n {\n ...,zset_outputintent(i_ctx_t * i_ctx_p)\n {\n ...,zset_outputintent(i_ctx_t * i_ctx_p)\n {\n ...,1,True,"[[(x, tensor([[ 0.0161, -0.0272, 0.0047, ......"
1,1,bigvul,179080,train,[],[35],"SYSCALL_DEFINE1(inotify_init1, int, flags)\n ...","SYSCALL_DEFINE1(inotify_init1, int, flags)\n ...","SYSCALL_DEFINE1(inotify_init1, int, flags)\n ...",1,True,"[[(x, tensor([[-0.0035, -0.0155, 0.0044, ......"
2,2,bigvul,179136,train,[116],"[7, 117, 118]","int wvlan_uil_put_info(struct uilreq *urq, st...","int wvlan_uil_put_info(struct uilreq *urq, st...","int wvlan_uil_put_info(struct uilreq *urq, st...",1,True,"[[(x, tensor([[-0.0107, -0.0186, -0.0028, ......"
3,3,bigvul,179169,train,"[19, 26]","[20, 27]","static int filter_frame(AVFilterLink *inlink,...","static int filter_frame(AVFilterLink *inlink,...","static int filter_frame(AVFilterLink *inlink,...",1,True,"[[(x, tensor([[ 0.0002, -0.0244, -0.0047, ......"
4,4,bigvul,179347,train,"[64, 65, 68, 72, 73, 76, 89, 94, 125]","[22, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 3...",static unsigned xen_netbk_tx_build_gops(struc...,static unsigned xen_netbk_tx_build_gops(struc...,static unsigned xen_netbk_tx_build_gops(struc...,1,True,"[[(x, tensor([[ 3.0888e-03, -2.1401e-02, 3.87..."

In [6]:
devign = pd.read_json("/root/autodl-tmp/vul-detect/data/raw/dataset.json")
devign.head()

,project,commit_id,target,func
0,FFmpeg,973b1a6b9070e2bf17d17568cbaf4043ce931f51,0,static av_cold int vdadec_init(AVCodecContext ...
1,FFmpeg,321b2a9ded0468670b7678b7c098886930ae16b2,0,static int transcode(AVFormatContext **output_...
2,FFmpeg,5d5de3eba4c7890c2e8077f5b4ae569671d11cf8,0,"static void v4l2_free_buffer(void *opaque, uin..."
3,FFmpeg,32bf6550cb9cc9f487a6722fe2bfc272a93c1065,0,"int ff_get_wav_header(AVFormatContext *s, AVIO..."
4,FFmpeg,57d77b3963ce1023eaf5ada8cba58b9379405cc8,0,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ..."

In [8]:
devign.shape

(27318, 4)

In [10]:
import glob
files = glob.glob("/root/autodl-tmp/vul-detect/utils/data/torch_geometrics_process/cfexplainer/storage/processed/Devign/code/*.c")
len(files)

4608

In [7]:
def Filter_raw_dataset(raw):

    # Here, taking the Devign dataset as an example,
    # specific modifications need to be made according to different dataset formats.
    print(f"=== Raw dataset size: {len(raw)} ===")
    filtered = data.apply_filter(raw, filter_select) # see "select" function above
    print(f"=== Filtered dataset size: {len(filtered)} ===")
    filtered = data.clean(filtered) # remove duplicates 
    print(f"=== Filtered and cleaned dataset size: {len(filtered)} ===")
    data.drop(filtered, ["hash", "commit_id", "project", "cwe"]) # Hash column name "hash" or "commit_id" depends on the dataset
    filtered['idx'] = filtered.index
    print(f"=== Filtered and cleaned dataset columns: {filtered.columns} ===")

    return filtered

Filter_raw_dataset(devign)

=== Raw dataset size: 27318 ===

AttributeError: 'DataFrame' object has no attribute 'apply_filter'

In [4]:
data.columns

Index(['idx', 'dataset', 'id', 'label', 'removed', 'added', 'diff', 'before',
       'after', 'vul', 'valid', 'torch_geometrics_data'],
      dtype='object')

已连接到 vul-detect (Python 3.9.21)

In [ ]:
data["torch_geometrics_data"][0][0]

Data(x=[117, 768], edge_index=[2, 199], _VULN=[117], _LINE=[117], _SAMPLE=[117], _GTYPE='ast')

In [ ]:
data["torch_geometrics_data"][0][0].edge_index

tensor([[  0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
           1,   1,   1,   1,   1,   1,   1,   2,   3,   4,   6,  11,  13,  14,
          15,  16,  17,  18,  19,  19,  20,  21,  21,  21,  21,  21,  22,  23,
          23,  24,  25,  26,  26,  27,  28,  28,  29,  30,  31,  31,  32,  33,
          33,  34,  35,  36,  37,  38,  38,  39,  40,  41,  41,  42,  42,  42,
          43,  44,  45,  45,  45,  46,  47,  48,  48,  49,  49,  50,  51,  51,
          51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,
          51,  51,  51,  51,  51,  55,  56,  59,  60,  63,  64,  67,  72,  72,
          72,  73,  74,  75,  76,  77,  77,  77,  80,  81,  82,  83,  84,  85,
          86,  86,  86,  86,  87,  87,  89,  90,  90,  91,  91,  91,  91,  92,
          93,  94,  95,  96,  96,  97,  97,  97,  97,  97,  97,  97,  97,  97,
          97,  97,  97,  97,  97,  97,  99, 100, 100, 104, 105, 105, 109, 110,
         110, 115, 116],
        [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  21,  28,  30,  31,  33,  35,  36,  37,
          38,  40,  41,  45,  48,  51,  72,  75,  76,  77,  80,  81,  82,  83,
          84,  85,  86,  95,  96, 115, 116,   2,   3,   4,   6,  11,  13,  14,
          15,  16,  17,  18,  19,  20,  20,  21,  22,  23,  25,  26,  22,  23,
          24,  24,  25,  26,  27,  27,  28,  29,  29,  30,  31,  32,  32,  33,
          34,  34,  35,  36,  37,  38,  39,  39,  40,  41,  42,  42,  43,  44,
          43,  44,  45,  46,  47,  46,  47,  48,  49,  49,  50,  50,  51,  52,
          53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
          67,  68,  69,  70,  71,  55,  56,  59,  60,  63,  64,  67,  72,  73,
          74,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
          86,  90,  87,  89,  87,  88,  89,  90,  91,  91,  92,  93,  94,  92,
          93,  94,  95,  96,  97,  97,  98,  99, 100, 102, 103, 104, 105, 107,
         108, 109, 110, 112, 113, 114,  99, 100, 101, 104, 105, 106, 109, 110,
         111, 115, 116]])

In [ ]:
data["torch_geometrics_data"][0][0].edge_index[0]

tensor([  0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   2,   3,   4,   6,  11,  13,  14,
         15,  16,  17,  18,  19,  19,  20,  21,  21,  21,  21,  21,  22,  23,
         23,  24,  25,  26,  26,  27,  28,  28,  29,  30,  31,  31,  32,  33,
         33,  34,  35,  36,  37,  38,  38,  39,  40,  41,  41,  42,  42,  42,
         43,  44,  45,  45,  45,  46,  47,  48,  48,  49,  49,  50,  51,  51,
         51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,  51,
         51,  51,  51,  51,  51,  55,  56,  59,  60,  63,  64,  67,  72,  72,
         72,  73,  74,  75,  76,  77,  77,  77,  80,  81,  82,  83,  84,  85,
         86,  86,  86,  86,  87,  87,  89,  90,  90,  91,  91,  91,  91,  92,
         93,  94,  95,  96,  96,  97,  97,  97,  97,  97,  97,  97,  97,  97,
         97,  97,  97,  97,  97,  97,  99, 100, 100, 104, 105, 105, 109, 110,
        110, 115, 116])

In [ ]:
type(data["torch_geometrics_data"][0][0].edge_index[0])

torch.Tensor

In [ ]:
data["torch_geometrics_data"][0][0].edge_index[0].shape

torch.Size([199])

In [ ]:
graph_data = {
                ('node', 'ast', 'node'): (data["torch_geometrics_data"][0][0].edge_index[0], data["torch_geometrics_data"][0][0].edge_index[1]),
                ('node', 'cfgcdg', 'node'): (data["torch_geometrics_data"][0][1].edge_index[0], data["torch_geometrics_data"][0][1].edge_index[1]),
                ('node', 'pdg', 'node'): (data["torch_geometrics_data"][0][2].edge_index[0], data["torch_geometrics_data"][0][2].edge_index[1])
            }
het_graph = dgl.heterograph(graph_data)

In [ ]:
het_graph

Graph(num_nodes={'node': 117},
      num_edges={('node', 'ast', 'node'): 199, ('node', 'cfgcdg', 'node'): 334, ('node', 'pdg', 'node'): 454},
      metagraph=[('node', 'node', 'ast'), ('node', 'node', 'cfgcdg'), ('node', 'node', 'pdg')])

In [ ]:
data["torch_geometrics_data"][0][0].x

tensor([[ 0.0161, -0.0272,  0.0047,  ..., -0.0196, -0.0699, -0.0344],
        [-0.0278,  0.0005,  0.0489,  ..., -0.0783, -0.0631, -0.0043],
        [-0.0099, -0.0376,  0.0407,  ..., -0.0036, -0.0370, -0.0257],
        ...,
        [ 0.0820, -0.0227, -0.0427,  ..., -0.0036,  0.0008,  0.0366],
        [ 0.0062, -0.0362,  0.0056,  ..., -0.0786, -0.0375, -0.0339],
        [ 0.0508, -0.0282, -0.0458,  ..., -0.0300, -0.0455, -0.0338]])

In [ ]:
data["torch_geometrics_data"][0][0].x.shape

torch.Size([117, 768])

In [ ]:
het_graph.ndata['feature'] = data["torch_geometrics_data"][0][0].x

In [ ]:
import torch

In [ ]:
import scipy.sparse as sp

In [ ]:
def sparse_mx_to_torch_sparse_tensor(sparse_mx):
    """Convert a scipy sparse matrix to a torch sparse tensor."""
    sparse_mx = sparse_mx.tocoo().astype(np.float32)
    indices = torch.from_numpy(
        np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.int64))
    values = torch.from_numpy(sparse_mx.data)
    shape = torch.Size(sparse_mx.shape)
    return torch.sparse.FloatTensor(indices, values, shape)

In [ ]:
def normalize_adj(row, col):
    """Symmetrically normalize adjacency matrix."""
    data = torch.ones(row.size(1))
    adj = sp.coo_matrix((data, (row, col)), shape=(het_graph.num_nodes(), het_graph.num_nodes(),))
    rowsum = np.array(adj.sum(1))

    d_inv_sqrt = np.power(rowsum, -0.5).flatten()
    d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.
    d_mat_inv_sqrt = sp.diags(d_inv_sqrt)
    return adj.dot(d_mat_inv_sqrt).transpose().dot(d_mat_inv_sqrt).tocoo()

In [ ]:
def normalize_adj(row, col):
    """Symmetrically normalize adjacency matrix."""
    data = torch.ones(row.size(0))

    adj = sp.coo_matrix((data, (row, col)), shape=(het_graph.num_nodes(), het_graph.num_nodes(),))
    rowsum = np.array(adj.sum(1))

    d_inv_sqrt = np.power(rowsum, -0.5).flatten()
    d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.
    d_mat_inv_sqrt = sp.diags(d_inv_sqrt)
    return adj.dot(d_mat_inv_sqrt).transpose().dot(d_mat_inv_sqrt).tocoo()

In [ ]:
import numpy as np

In [ ]:
normalize_adj(data["torch_geometrics_data"][0][0].edge_index[0], data["torch_geometrics_data"][0][0].edge_index[1])

<ipython-input-30-0d254a890e93>:8: RuntimeWarning: divide by zero encountered in power
  d_inv_sqrt = np.power(rowsum, -0.5).flatten()

<117x117 sparse matrix of type '<class 'numpy.float32'>'
	with 166 stored elements in COOrdinate format>

In [ ]:
meta_path_adj_with_normalize_adj = {
                'ast': sparse_mx_to_torch_sparse_tensor(normalize_adj(data["torch_geometrics_data"][0][0].edge_index[0], data["torch_geometrics_data"][0][0].edge_index[1])),
                'cfgcdg': sparse_mx_to_torch_sparse_tensor(normalize_adj(data["torch_geometrics_data"][0][1].edge_index[0], data["torch_geometrics_data"][0][1].edge_index[1])),
                'pdg': sparse_mx_to_torch_sparse_tensor(normalize_adj(data["torch_geometrics_data"][0][2].edge_index[0], data["torch_geometrics_data"][0][2].edge_index[1]))
            }

<ipython-input-30-0d254a890e93>:8: RuntimeWarning: divide by zero encountered in power
  d_inv_sqrt = np.power(rowsum, -0.5).flatten()
<ipython-input-26-064c30c72962>:8: UserWarning: torch.sparse.SparseTensor(indices, values, shape, *, device=) is deprecated.  Please use torch.sparse_coo_tensor(indices, values, shape, dtype=, device=). (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:605.)
  return torch.sparse.FloatTensor(indices, values, shape)

In [ ]:
meta_path_adj_with_normalize_adj['ast']

tensor(indices=tensor([[  0,   1,   2,   3,   4,   6,  11,  13,  14,  15,  16,
                         17,  18,  19,  21,  28,  30,  31,  33,  35,  36,  37,
                         38,  40,  41,  45,  48,  51,  72,  75,  76,  77,  80,
                         81,  82,  83,  84,  85,  86,  95,  96, 115, 116,   2,
                          3,   4,   6,  11,  13,  14,  15,  16,  17,  18,  19,
                         20,  20,  21,  22,  23,  25,  26,  22,  23,  24,  24,
                         25,  26,  27,  27,  28,  29,  29,  30,  31,  32,  32,
                         33,  34,  34,  35,  36,  37,  38,  39,  39,  40,  41,
                         42,  42,  43,  44,  43,  44,  45,  46,  47,  46,  47,
                         48,  49,  49,  50,  50,  51,  55,  56,  59,  60,  63,
                         64,  67,  55,  56,  59,  60,  63,  64,  67,  72,  73,
                         74,  73,  74,  75,  76,  77,  80,  81,  82,  83,  84,
                         85,  86,  87,  89,  90,  87,  89,  90,  91,  91,  92,
                         93,  94,  92,  93,  94,  95,  96,  97,  97,  99, 100,
                        104, 105, 109, 110,  99, 100, 104, 105, 109, 110, 115,
                        116],
                       [  0,   0,   1,   1,   1,   1,   1,   1,   1,   1,   1,
                          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
                          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
                          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,
                          3,   4,   6,  11,  13,  14,  15,  16,  17,  18,  19,
                         19,  20,  21,  21,  21,  21,  21,  22,  23,  23,  24,
                         25,  26,  26,  27,  28,  28,  29,  30,  31,  31,  32,
                         33,  33,  34,  35,  36,  37,  38,  38,  39,  40,  41,
                         41,  42,  42,  42,  43,  44,  45,  45,  45,  46,  47,
                         48,  48,  49,  49,  50,  51,  51,  51,  51,  51,  51,
                         51,  51,  55,  56,  59,  60,  63,  64,  67,  72,  72,
                         72,  73,  74,  75,  76,  77,  80,  81,  82,  83,  84,
                         85,  86,  86,  86,  86,  87,  89,  90,  90,  91,  91,
                         91,  91,  92,  93,  94,  95,  96,  96,  97,  97,  97,
                         97,  97,  97,  97,  99, 100, 104, 105, 109, 110, 115,
                        116]]),
       values=tensor([0.5000, 0.1031, 0.1459, 0.1459, 0.1459, 0.1459, 0.1459,
                      0.1459, 0.1459, 0.1459, 0.1459, 0.1459, 0.1459, 0.1031,
                      0.0652, 0.1031, 0.1459, 0.1031, 0.1031, 0.1459, 0.1459,
                      0.1459, 0.1031, 0.1459, 0.1031, 0.0842, 0.1031, 0.0318,
                      0.0842, 0.1459, 0.1459, 0.0842, 0.1459, 0.1459, 0.1459,
                      0.1459, 0.1459, 0.1459, 0.0729, 0.1459, 0.1031, 0.1459,
                      0.1459, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
                      1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.5000, 0.7071,
                      1.0000, 0.2000, 0.4472, 0.3162, 0.4472, 0.3162, 1.0000,
                      0.5000, 0.7071, 1.0000, 1.0000, 0.5000, 0.7071, 1.0000,
                      0.5000, 0.7071, 1.0000, 1.0000, 0.5000, 0.7071, 1.0000,
                      0.5000, 0.7071, 1.0000, 1.0000, 1.0000, 1.0000, 0.5000,
                      0.7071, 1.0000, 1.0000, 0.5000, 0.4082, 0.3333, 0.5774,
                      0.5774, 1.0000, 1.0000, 0.3333, 0.5774, 0.5774, 1.0000,
                      1.0000, 0.5000, 0.5000, 0.5000, 0.7071, 1.0000, 0.0476,
                      0.2182, 0.2182, 0.2182, 0.2182, 0.2182, 0.2182, 0.2182,
                      1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
                      0.3333, 0.5774, 0.5774, 1.0000, 1.0000, 1.0000, 1.0000,
                      0.3333, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
                      0.2500, 0.3536, 0.5000, 0.3536, 0.5000, 1.0000, 0.5000,
                      0.3536, 0.2500, 0.5000, 0.5000, 0.5000, 1.0000, 1.0000,
                      1.0000, 1.0000, 0.5000, 0.1826, 0.0667, 0.2582, 0.1826,
                      0.2582, 0.1826, 0.2582, 0.1826, 1.0000, 0.5000, 1.0000,
                      0.5000, 1.0000, 0.5000, 1.0000, 1.0000]),
       size=(117, 117), nnz=166, layout=torch.sparse_coo)

In [ ]:
def re_featuresv2(adj, features, K, start_hops=0):
    nodes_features = torch.empty(features.shape[0], 1, K + 1 - start_hops, features.shape[1])

    for i in range(features.shape[0]):  # self
        nodes_features[i, 0, 0, :] = features[i]

    x = features + torch.zeros_like(features)

    for i in range(K):  # 0:1-hop，1：2:-hop....k-1:K-hop

        x = torch.matmul(adj, x)
        if i >= start_hops:
            for index in range(features.shape[0]):
                nodes_features[index, 0, i + 1 - start_hops, :] = x[index]

    nodes_features = nodes_features.squeeze()
    return nodes_features  # size= (N, 1, K+1-start_hops, d )

In [ ]:
multi_hop_features = None
for max_hop in range(1, 10):
    multi_hop_features_with_process_feature_with_normalize_adj = [re_featuresv2(adj=meta_path_adj_with_normalize_adj[mp], features=data["torch_geometrics_data"][0][0].x, K=max_hop, start_hops=0) for mp in meta_path_adj_with_normalize_adj]

    multi_hop_features_with_process_feature_with_normalize_adj = torch.stack(multi_hop_features_with_process_feature_with_normalize_adj).permute(1, 0, 2, 3)
    if max_hop == 9:
        multi_hop_features = multi_hop_features_with_process_feature_with_normalize_adj

In [ ]:
het_graph.ndata['multi_hop_feature'] = multi_hop_features

In [ ]:
het_graph

Graph(num_nodes={'node': 117},
      num_edges={('node', 'ast', 'node'): 199, ('node', 'cfgcdg', 'node'): 334, ('node', 'pdg', 'node'): 454},
      metagraph=[('node', 'node', 'ast'), ('node', 'node', 'cfgcdg'), ('node', 'node', 'pdg')])